name: birex
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flex_color_scheme: ^8.0.2
  dart_ssi: ^3.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.6.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3
  logger: ^2.5.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  curl_logger_dio_interceptor: ^1.0.0
  qr_code_dart_scan: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  very_good_analysis: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
